import { EventConfig, AgendaSession, PostItem, AuthorProfile } from './types';

export const INITIAL_EVENT_CONFIG: EventConfig = {
  title: 'SaaS Frontiers Annual Summit 2025',
  hostCompany: 'CloudVentures Inc.',
  date: 'Oct 24-26, 2025',
  venue: 'Moscone Center & Hybrid',
  tags: ['#SaaSSummit25', '#B2BGrowth', '#AIWorkflows', '#TechLeadership', '#EventPulse'],
  linkedinUrl: 'https://linkedin.com/company/eventpulse',
  twitterHandle: '@EventPulseHQ',
  websiteUrl: 'https://eventpulse.live/summit25',
  generatedCount: 1248,
  totalReach: '342.5K',
  topTag: '#SaaS25',
  pulseVelocity: 'Peak 92 posts/hr',
};

export const INITIAL_AUTHOR_PROFILE: AuthorProfile = {
  name: 'Alex Rivera',
  title: 'Senior Product Lead at ApexTech',
  avatar: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCysuiTGUsh62gpQgsvEZQRofC7XtpahdIVZCmR0YhQrAg9VGmvXPMW9q6gP_9RjHUZ1T29DCCR3so5hlaaDD4NCAsNsgSuGvB9knVlnqc_HYe1LbaQQHxGwXVZqaQQO0yXcgdTzc_fFuNdJxTClPSBIFsub48gzvBsKufd6GngeNltxt_0HnDE29nTTcrWvyX0PdEVjvcLZ3B4j-nKV1HcUxtLO3Teh-Lgcx0TiFN82NZQ-K3GgCWZ',
  connectionDegree: '1st',
};

export const SAMPLE_IMAGES = [
  {
    id: 'stage-keynote',
    url: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBEJiHo7optCveROIGWiYPzw45e6cTJLnvqciYnFKcHkC16h5Qn_NLZOskoYk-Hq0iFC6FZy7NtbT-dKKVSSE5AraS8-T4s7h4GgUzFATiSKQvnqbwLbVrUkLnV2uVwkWBJuv5bBbcy1pmCuJCNHTcJSC1peyfJHrE3vjn8ewyBSBhNyZ7xLA1v8fScr9E3101npVr72rCNAi9j3AsoW4f3BpdLLZNHhTMXb9FnWWnPkyE63cRJu9kt',
    caption: 'Main Keynote Stage • Purple Ambience',
    label: 'Stage Overview',
  },
  {
    id: 'sarah-speaking',
    url: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCOFgVd9iX2bmuUht-aE2lec1SdDKAodVUPWsWonYm4htsVesVbPL1kfmD7o190Mu8--Spchpek8etEd2LS1l6KrmMvbhuZp9DSAE613QYUiJfS8lTn7jFuFZIiZAgK0jD48j3z8tl4poOngXy3frlY9TLfbNuyJIkDtuv0HXgZGP5ra_T61TRCYDTErNPcnBgfJ5q63bd3lcPLowFrPWNq_GfueUkL_vjKmwG4ikNsAKhPBYrNLiM3',
    caption: 'Sarah Chen Keynote • Autonomous Agentic Systems',
    label: 'Keynote Speaker',
  },
  {
    id: 'diagram-slide',
    url: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDgLC0Nw2ucpc2cIZGz8iGPqhA07-HIzVAow0TuZKqdPqD5SS1olaWHY47OcBe1a1FFu10GD10FxBkXdcYwB5jjlc-3QXqgXH000vc0nt-h6YRUPUJlJpMWtRTK8ZL8G_EWzWQiBRAF2fR9DusM9ixYT8n52_n5Csw5chro9dyl0Pr120FgZHzKjUC6Qnpe4HFUlZI_zWu4vK9_r7hQbWzdnq3md6D4JzYxSJVz9QoIQoYNYiGOOglC',
    caption: 'Attendee Generator Workflow Slide • Hall A',
    label: 'Workflow Architecture',
  },
];

export const AGENDA_SESSIONS: AgendaSession[] = [
  {
    id: 'session-1',
    title: 'Autonomous Agentic Workflows & Multi-Agent Systems',
    speaker: 'Sarah Chen',
    speakerRole: 'VP of AI Architecture at Anthropic & CloudVentures',
    time: '10:00 AM - 11:15 AM PST',
    room: 'Hall A (Main Keynote Stage)',
    isLive: true,
    tags: ['#AgenticAI', '#SaaSSummit25', '#AIWorkflows'],
    keyHighlights: 'Unbelievable keynote on the future of autonomous agentic workflows by Sarah Chen! 3 main takeaways on scaling multi-agent architecture and customer value.',
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDgLC0Nw2ucpc2cIZGz8iGPqhA07-HIzVAow0TuZKqdPqD5SS1olaWHY47OcBe1a1FFu10GD10FxBkXdcYwB5jjlc-3QXqgXH000vc0nt-h6YRUPUJlJpMWtRTK8ZL8G_EWzWQiBRAF2fR9DusM9ixYT8n52_n5Csw5chro9dyl0Pr120FgZHzKjUC6Qnpe4HFUlZI_zWu4vK9_r7hQbWzdnq3md6D4JzYxSJVz9QoIQoYNYiGOOglC',
    imageCaption: 'Sarah Chen Keynote • Hall A',
  },
  {
    id: 'session-2',
    title: 'From PLG to Enterprise AI Sales Playbooks',
    speaker: 'Marcus Vance',
    speakerRole: 'Chief Revenue Officer at CloudScale Capital',
    time: '11:30 AM - 12:30 PM PST',
    room: 'Hall B (Growth Stage)',
    isLive: false,
    tags: ['#B2BGrowth', '#ProductLed', '#SaaSSummit25'],
    keyHighlights: 'How product-led software companies are closing 7-figure enterprise contracts without bloated outbound armies. Key lesson: product signals beat cold outreach.',
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBEJiHo7optCveROIGWiYPzw45e6cTJLnvqciYnFKcHkC16h5Qn_NLZOskoYk-Hq0iFC6FZy7NtbT-dKKVSSE5AraS8-T4s7h4GgUzFATiSKQvnqbwLbVrUkLnV2uVwkWBJuv5bBbcy1pmCuJCNHTcJSC1peyfJHrE3vjn8ewyBSBhNyZ7xLA1v8fScr9E3101npVr72rCNAi9j3AsoW4f3BpdLLZNHhTMXb9FnWWnPkyE63cRJu9kt',
    imageCaption: 'Marcus Vance • Hall B Growth',
  },
  {
    id: 'session-3',
    title: 'Context Grounding, Real-time APIs & Guardrails',
    speaker: 'Elena Rostova',
    speakerRole: 'Head of Infrastructure at Pulse Labs',
    time: '02:00 PM - 03:15 PM PST',
    room: 'Grand Ballroom C',
    isLive: false,
    tags: ['#TechLeadership', '#LLMOps', '#SaaSSummit25'],
    keyHighlights: 'Why parameter scale is plateauing in enterprise ROI while low-latency grounded retrieval pipelines are delivering 99.8% reliability for production agents.',
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCOFgVd9iX2bmuUht-aE2lec1SdDKAodVUPWsWonYm4htsVesVbPL1kfmD7o190Mu8--Spchpek8etEd2LS1l6KrmMvbhuZp9DSAE613QYUiJfS8lTn7jFuFZIiZAgK0jD48j3z8tl4poOngXy3frlY9TLfbNuyJIkDtuv0HXgZGP5ra_T61TRCYDTErNPcnBgfJ5q63bd3lcPLowFrPWNq_GfueUkL_vjKmwG4ikNsAKhPBYrNLiM3',
    imageCaption: 'Elena Rostova • Infrastructure Track',
  },
];

export const INITIAL_POSTS: PostItem[] = [
  {
    id: 'post-1',
    authorName: 'Alex Rivera',
    authorRole: 'Senior Product Lead at ApexTech',
    authorAvatar: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCysuiTGUsh62gpQgsvEZQRofC7XtpahdIVZCmR0YhQrAg9VGmvXPMW9q6gP_9RjHUZ1T29DCCR3so5hlaaDD4NCAsNsgSuGvB9knVlnqc_HYe1LbaQQHxGwXVZqaQQO0yXcgdTzc_fFuNdJxTClPSBIFsub48gzvBsKufd6GngeNltxt_0HnDE29nTTcrWvyX0PdEVjvcLZ3B4j-nKV1HcUxtLO3Teh-Lgcx0TiFN82NZQ-K3GgCWZ',
    timeAgo: '3h',
    content: `Still energized from day 2 at #SaaSSummit25 hosted by @CloudVentures! 🚀\n\nHuge inspiration listening to Sarah Chen breaking down practical AI agent architectures. Key takeaways:\n\n1. Multi-agent workflows are shifting from experimental to mission-critical.\n2. Context grounding > raw model parameter size.\n3. User trust is earned through predictable UX.\n\nGrateful for the incredible conversations with fellow founders and builders! Looking forward to tomorrow's sessions.\n\n#SaaSSummit25 #B2BGrowth #AIWorkflows #TechLeadership #EventPulse`,
    tags: ['#SaaSSummit25', '#B2BGrowth', '#AIWorkflows', '#TechLeadership', '#EventPulse'],
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDgLC0Nw2ucpc2cIZGz8iGPqhA07-HIzVAow0TuZKqdPqD5SS1olaWHY47OcBe1a1FFu10GD10FxBkXdcYwB5jjlc-3QXqgXH000vc0nt-h6YRUPUJlJpMWtRTK8ZL8G_EWzWQiBRAF2fR9DusM9ixYT8n52_n5Csw5chro9dyl0Pr120FgZHzKjUC6Qnpe4HFUlZI_zWu4vK9_r7hQbWzdnq3md6D4JzYxSJVz9QoIQoYNYiGOOglC',
    imageCaption: 'Sarah Chen Keynote • Hall A',
    reactionsCount: 142,
    commentsCount: 28,
    repostsCount: 6,
    isLiked: false,
    status: 'stage_featured',
    platform: 'linkedin',
  },
  {
    id: 'post-2',
    authorName: 'Danielle Brooks',
    authorRole: 'Head of Growth at HyperWave',
    authorAvatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=256&q=80',
    timeAgo: '1h',
    content: `The vibe at Moscone Center right now is unreal. Overheard in the hallway: "If your AI agent isn't connected to live user context, you are building yesterday's demo."\n\nKudos to @CloudVentures for prioritizing real practitioner playbooks over vendor pitches.\n\n#SaaSSummit25 #PLG #ProductLed #B2BGrowth`,
    tags: ['#SaaSSummit25', '#PLG', '#ProductLed', '#B2BGrowth'],
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBEJiHo7optCveROIGWiYPzw45e6cTJLnvqciYnFKcHkC16h5Qn_NLZOskoYk-Hq0iFC6FZy7NtbT-dKKVSSE5AraS8-T4s7h4GgUzFATiSKQvnqbwLbVrUkLnV2uVwkWBJuv5bBbcy1pmCuJCNHTcJSC1peyfJHrE3vjn8ewyBSBhNyZ7xLA1v8fScr9E3101npVr72rCNAi9j3AsoW4f3BpdLLZNHhTMXb9FnWWnPkyE63cRJu9kt',
    imageCaption: 'Packed Stage • Hall A',
    reactionsCount: 94,
    commentsCount: 14,
    repostsCount: 3,
    isLiked: true,
    status: 'published',
    platform: 'linkedin',
  },
  {
    id: 'post-3',
    authorName: 'Kenji Sato',
    authorRole: 'Founding Partner at Zenith Ventures',
    authorAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=256&q=80',
    timeAgo: '45m',
    content: `Keynote synthesis from #SaaSSummit25:\n\nThe next billion-dollar software category isn't a new foundation model. It's the workflow glue that makes autonomous agents accountable to enterprise security policies.\n\nWho is building in this layer? My DMs are open. Ping me if you are here in SF today! ☕`,
    tags: ['#SaaSSummit25', '#VentureCapital', '#EnterpriseSoftware'],
    reactionsCount: 218,
    commentsCount: 47,
    repostsCount: 12,
    isLiked: false,
    status: 'queued',
    platform: 'linkedin',
  },
];
